# dev环境
server:
  port: 8080

spring:
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/foodie?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

mybatis-plus:
  mapper-locations: classpath:group/foodie/dao/mapper/*Mapper
  #开启sql日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  file: /export/log/foodie/foodie_detail.log
  rootLevel: info


